services:
  sap-script-web:
    build: .
    container_name: sap-script-web
    ports:
      - "8010:8000"
    env_file:
      - ../.env
    environment:
      DATA_DIR: /data
      SAP_SCRIPT_PROJECT_DIR: /sap-script
      UPLOADS_DIR: /uploads
      UPLOADS_WINDOWS_DIR: 'C:\workspace\sap-script\sap_script_uploads'
      JIRA_DOWNLOAD_DIR_CONTAINER: /data/jira
      JIRA_DOWNLOAD_DIR_WINDOWS: 'C:\Jira'
    volumes:
      - sap_script_data:/data
      - ..:/sap-script:ro
      - ../sap_script_uploads:/uploads
      - ./web_api:/srv/sap-script-web/web_api
      - C:/Jira:/data/jira
    restart: unless-stopped

volumes:
  sap_script_data:
